### ISSUE TITLE
Unable to use the OSS chart in an airgapped environment

### ISSUE THREAD

**Issue by RangerRick** [netbox-community/netbox-chart#431] opened 2024-12-03 19:24 UTC
### The Helm chart version

current beta in develop

### Environment Versions

```text
Helm 3.16.3
```

### Custom chart values

```yaml
N/A
```

### Current Behavior & Steps to Reproduce

When in an airgapped environment without internet access, `helm lint` on any `values.yaml` fails, because of the schema references in `values.schema.json` which point to `raw.githubusercontent.com`.  I have tried several variations on changing `$ref` values to point to local copies of the subchart schemas, but to no avail.

_Also_, we are currently pointing to the `master` versions of the subcharts' schemas, but we are not necessarily actually using the same version that master would point to, so it is possible there would be drift between the two.

### Expected Behavior

Ideally we would validate against all the schemas, together, without needing to hit the internet. Perhaps [this tool for merging](https://github.com/fastify/merge-json-schemas) as part of our build?  Maybe we could write something that actually uses the schema file inside the actual subcharts' tarball instead of relying on master still being valid.

**Comment by LeoColomb** [comment] 2024-12-03 21:14
Duplicate of #413

**Closed** 2024-12-05 22:46 UTC
Labels: bug
