### ISSUE TITLE
Error at database migrations

### ISSUE THREAD

**Issue by rhizoet** [netbox-community/netbox-chart#361] opened 2024-09-30 14:46 UTC
I am trying to roll out netbox on a 1.30.5 cluster with flux. This works so far, but I get the following and similar errors during database migration:

```
2024-09-30 14:17:04.625 GMT [166] ERROR:  relation "django_content_type" does not exist at character 106                                                       
2024-09-30 14:17:04.625 GMT [166] STATEMENT:  SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_
content_type" WHERE (("django_content_type"."app_label" = 'auth' AND "django_content_type"."model" IN ('permission', 'group')) OR ("django_content_type"."app_l
abel" = 'contenttypes' AND "django_content_type"."model" IN ('contenttype')) OR ("django_content_type"."app_label" = 'sessions' AND "django_content_type"."mode
l" IN ('session')) OR ("django_content_type"."app_label" = 'social_django' AND "django_content_type"."model" IN ('association', 'usersocialauth', 'nonce', 'par
tial', 'code')) OR ("django_content_type"."app_label" = 'taggit' AND "django_content_type"."model" IN ('tag', 'taggeditem')) OR ("django_content_type"."app_lab
el" = 'core' AND "django_content_type"."model" IN ('datafile', 'managedfile', 'autosyncrecord', 'objectchange', 'job', 'datasource', 'configrevision')) OR ("dj
ango_content_type"."app_label" = 'users' AND "django_content_type"."model" IN ('token', 'user', 'userconfig', 'objectpermission', 'group')) OR ("django_content
_type"."app_label" = 'circuits' AND "django_content_type"."model" IN ('provider', 'circuittermination', 'provideraccount', 'providernetwork', 'circuit', 'circu
itgroup', 'circuittype', 'circuitgroupassignment')) OR ("django_content_type"."app_label" = 'dcim' AND "django_content_type"."model" IN ('module', 'powerport',
 'cable', 'location', 'interface', 'inventoryitem', 'cabletermination', 'devicebaytemplate', 'devicetype', 'poweroutlettemplate', 'inventoryitemtemplate', 'int
erfacetemplate', 'rackreservation', 'cablepath', 'platform', 'rearport', 'modulebaytemplate', 'manufacturer', 'inventoryitemrole', 'racktype', 'virtualdeviceco
ntext', 'powerfeed', 'region', 'consoleport', 'device', 'consoleserverport', 'devicerole', 'powerpanel', 'poweroutlet', 'rearporttemplate', 'consoleporttemplat
e', 'frontporttemplate', 'rackrole', 'site', 'devicebay', 'sitegroup', 'consoleserverporttemplate', 'powerporttemplate', 'modulebay', 'frontport', 'moduletype'
, 'rack', 'virtualchassis')) OR ("django_content_type"."app_label" = 'ipam' AND "django_content_type"."model" IN ('iprange', 'vlangroup', 'asnrange', 'rir', 'r
ole', 'routetarget', 'fhrpgroupassignment', 'aggregate', 'prefix', 'ipaddress', 'vrf', 'service', 'vlan', 'fhrpgroup', 'asn', 'servicetemplate')) OR ("django_c
ontent_type"."app_label" = 'extras' AND "django_content_type"."model" IN ('eventrule', 'customfieldchoiceset', 'tag', 'subscription', 'notification', 'dashboar
d', 'configtemplate', 'stagedchange', 'branch', 'script', 'journalentry', 'bookmark', 'customfield', 'savedfilter', 'configcontext', 'notificationgroup', 'expo
rttemplate', 'customlink', 'webhook', 'imageattachment', 'cachedvalue', 'taggeditem')) OR ("django_content_type"."app_label" = 'tenancy' AND "django_content_ty
pe"."model" IN ('tenant', 'contactassignment', 'contactrole', 'contact', 'contactgroup', 'tenantgroup')) OR ("django_content_type"."app_label" = 'virtualizatio
n' AND "django_content_type"."model" IN ('vminterface', 'clustertype', 'clustergroup', 'cluster', 'virtualmachine', 'virtualdisk')) OR ("django_content_type"."
app_label" = 'vpn' AND "django_content_type"."model" IN ('tunneltermination', 'ikeproposal', 'ikepolicy', 'l2vpn', 'ipsecproposal', 'tunnelgroup', 'ipsecprofil
e', 'tunnel', 'ipsecpolicy', 'l2vpntermination')) OR ("django_content_type"."app_label" = 'wireless' AND "django_content_type"."model" IN ('wirelesslangroup', 
'wirelesslan', 'wirelesslink')) OR ("django_content_type"."app_label" = 'django_rq' AND "django_content_type"."model" IN ('queue')))
```

I can't understand exactly where the error is coming from. I have already adjusted the resources, but this makes no difference.

I am using the current Chart 5.0.0-beta.107 and, as mentioned above, a current cluster with version 1.30.5.

At a certain point it stops and the helmrelease starts all over again. I have also tried both the database from the chart and an external one.

**Comment by rhizoet** [comment] 2024-09-30 15:29
Ok, apparently you have to set the `resourcesPreset` to `xlarge` so that all migrations can be carried out accordingly. Even `large` is not sufficient. And the pod runs on a node with 4 cores and 8 gigs of RAM.

Wouldn't it make sense to set `xlarge` as default?

**Comment by LeoColomb** [comment] 2024-09-30 16:55
> Wouldn't it make sense to set `xlarge` as default?

Sounds good, don't hesitate to open a pull request.

**Comment by LeoColomb** [comment] 2024-10-03 09:00
Closing as duplicate of #316

**Closed by LeoColomb** 2024-10-03 09:00 UTC
Labels: bug
